
const STORAGE_KEY = 'browser-native-orchestrator-mobile-v2';
const APP_VERSION = '2.0.0';

const STAGES = [
  { id: 'planner', role: 'planner', title: 'Plan app architecture' },
  { id: 'architect', role: 'architect', title: 'Define architecture' },
  { id: 'builder', role: 'builder', title: 'Generate source files' },
  { id: 'critic', role: 'critic', title: 'Review for gaps' },
  { id: 'tester', role: 'tester', title: 'Run validation checks' },
  { id: 'packager', role: 'packager', title: 'Package handoff bundle' },
  { id: 'runner', role: 'runner', title: 'Run virtual device preview' },
];

function makeStageTask(stage, index) {
  return {
    id: stage.id,
    title: `${index + 1}. ${stage.title}`,
    role: stage.role,
    status: 'queued',
    notes: [],
  };
}

function makeWorker(stage) {
  const labels = {
    planner: 'Planner',
    architect: 'Architect',
    builder: 'Builder',
    critic: 'Critic',
    tester: 'Tester',
    packager: 'Packager',
    runner: 'Runner',
  };
  const roles = {
    planner: 'Breaks work into steps',
    architect: 'Shapes project structure',
    builder: 'Generates source files',
    critic: 'Finds gaps and issues',
    tester: 'Validates the output',
    packager: 'Prepares handoff bundles',
    runner: 'Drives the virtual device',
  };
  return { id: stage.id, name: labels[stage.role], role: roles[stage.role], status: 'Ready' };
}

function makeInitialFiles(projectName, goal, prompt) {
  return [
    {
      path: 'src/App.tsx',
      kind: 'code',
      content: generateAppSource(projectName, goal, prompt),
    },
    {
      path: 'src/lib/orchestrator.ts',
      kind: 'code',
      content: generateOrchestratorSource(),
    },
    {
      path: 'manifest.json',
      kind: 'config',
      content: JSON.stringify({
        name: projectName,
        version: '1.0.0',
        entry: 'src/App.tsx',
        packageName: 'com.example.browsernativeorchestrator',
      }, null, 2),
    },
    {
      path: 'bridge/native-bridge-manifest.json',
      kind: 'config',
      content: JSON.stringify({
        bridgeUrl: 'browser-native',
        installEndpoint: '/install',
        runEndpoint: '/run',
        bundleEndpoint: '/export',
      }, null, 2),
    },
    {
      path: 'README.md',
      kind: 'doc',
      content: `# ${projectName}\n\n${goal}\n\nThis project was generated by the browser-native compiler workflow.`,
    },
  ];
}

const DEFAULT_PROJECT_NAME = 'Browser Native Orchestrator';
const DEFAULT_GOAL = 'Create and package apps with a browser-first compiler workflow, manage source files, and simulate install/run actions in a virtual device lab.';
const DEFAULT_PROMPT = 'Build a mobile-first app factory with a project manager, file editor, task list, logs, export/import, and a virtual device lab. Use a dark clean interface and make the main actions easy to reach on mobile.';

const DEFAULTS = {
  projectName: DEFAULT_PROJECT_NAME,
  goal: DEFAULT_GOAL,
  prompt: DEFAULT_PROMPT,
  packageName: 'com.example.browsernativeorchestrator',
  packageVersion: '1.0.0',
  packageScreen: 'Welcome to Browser Native Orchestrator',
  buildStatus: 'idle',
  deviceState: 'ready',
  deviceScreen: 'Welcome to Browser Native Orchestrator',
  currentTask: 'Idle',
  selectedFile: 'src/App.tsx',
  selectedWorker: 'planner',
  taskInput: '',
  searchText: '',
  commandValue: 'devices',
  commandOutput: '',
  previewEnabled: true,
  phoneMode: true,
  exportCount: 0,
  savedAt: '',
  bundleName: '',
  tasks: STAGES.map((stage, index) => makeStageTask(stage, index)),
  workers: STAGES.map(makeWorker),
  files: makeInitialFiles(DEFAULT_PROJECT_NAME, DEFAULT_GOAL, DEFAULT_PROMPT),
  logs: [
    { id: 1, text: 'Mobile workspace loaded.', time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) },
    { id: 2, text: 'Ready for browser-based app creation.', time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) },
  ],
  installedApps: [],
};

let state = clone(DEFAULTS);
let activeTab = 'build';
let deferredPrompt = null;

const qs = (id) => document.getElementById(id);

function nowTime() {
  return new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
}

function clone(value) {
  return JSON.parse(JSON.stringify(value));
}

function escapeHtml(text) {
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function generateAppSource(projectName, goal, prompt) {
  const title = escapeHtml(projectName);
  const goalText = escapeHtml(goal);
  const promptText = escapeHtml(prompt);
  return `export default function App() {\n  return (\n    <main style={{ padding: 16, fontFamily: 'system-ui, sans-serif', lineHeight: 1.5 }}>\n      <h1>${title}</h1>\n      <p>${goalText}</p>\n      <section style={{ marginTop: 16 }}>\n        <h2>Compiler prompt</h2>\n        <p>${promptText}</p>\n      </section>\n      <section style={{ marginTop: 16 }}>\n        <h2>Compiler stages</h2>\n        <ul>\n          <li>Plan</li>\n          <li>Architect</li>\n          <li>Build</li>\n          <li>Review</li>\n          <li>Test</li>\n          <li>Package</li>\n          <li>Run</li>\n        </ul>\n      </section>\n    </main>\n  );\n}`;
}

function generateOrchestratorSource() {
  return `export function orchestrate(tasks) {\n  return tasks.map((task, index) => ({\n    id: index + 1,\n    task,\n    status: 'queued',\n  }));\n}`;
}

function normalizeTask(task, index) {
  if (typeof task === 'string') {
    return { id: `task-${index + 1}`, title: task, role: 'builder', status: 'queued', notes: [] };
  }
  return {
    id: task.id || `task-${index + 1}`,
    title: task.title || task.name || `Task ${index + 1}`,
    role: task.role || 'builder',
    status: task.status || 'queued',
    notes: Array.isArray(task.notes) ? task.notes : [],
  };
}

function normalizeFile(file) {
  if (!file) return null;
  return {
    path: file.path,
    kind: file.kind || 'code',
    content: String(file.content ?? ''),
  };
}

function normalizeState(input) {
  const base = clone(DEFAULTS);
  if (!input || typeof input !== 'object') return base;

  const merged = Object.assign(base, input);

  merged.tasks = Array.isArray(input.tasks) && input.tasks.length
    ? input.tasks.map(normalizeTask)
    : clone(DEFAULTS.tasks);

  merged.workers = Array.isArray(input.workers) && input.workers.length
    ? input.workers.map((worker, index) => ({
        id: worker.id || `worker-${index + 1}`,
        name: worker.name || `Worker ${index + 1}`,
        role: worker.role || 'Ready',
        status: worker.status || 'Ready',
      }))
    : clone(DEFAULTS.workers);

  merged.files = Array.isArray(input.files) && input.files.length
    ? input.files.map(normalizeFile).filter(Boolean)
    : clone(DEFAULTS.files);

  merged.logs = Array.isArray(input.logs)
    ? input.logs.map((log, index) => ({
        id: log.id ?? index + 1,
        text: String(log.text ?? ''),
        time: String(log.time ?? nowTime()),
      })).slice(-80)
    : clone(DEFAULTS.logs);

  merged.installedApps = Array.isArray(input.installedApps) ? input.installedApps.map((app) => ({
    name: String(app.name ?? DEFAULT_PROJECT_NAME),
    packageName: String(app.packageName ?? merged.packageName),
    version: String(app.version ?? merged.packageVersion ?? '1.0.0'),
    running: Boolean(app.running),
    lastLaunched: app.lastLaunched || null,
  })) : [];

  merged.selectedFile = typeof input.selectedFile === 'string' ? input.selectedFile : DEFAULTS.selectedFile;
  merged.selectedWorker = typeof input.selectedWorker === 'string' ? input.selectedWorker : DEFAULTS.selectedWorker;
  merged.taskInput = typeof input.taskInput === 'string' ? input.taskInput : '';
  merged.searchText = typeof input.searchText === 'string' ? input.searchText : '';
  merged.commandValue = typeof input.commandValue === 'string' ? input.commandValue : 'devices';
  merged.commandOutput = typeof input.commandOutput === 'string' ? input.commandOutput : '';
  merged.previewEnabled = input.previewEnabled !== false;
  merged.phoneMode = input.phoneMode !== false;
  merged.exportCount = Number.isFinite(Number(input.exportCount)) ? Number(input.exportCount) : 0;
  merged.savedAt = typeof input.savedAt === 'string' ? input.savedAt : '';
  merged.bundleName = typeof input.bundleName === 'string' ? input.bundleName : '';
  merged.currentTask = typeof input.currentTask === 'string' ? input.currentTask : 'Idle';

  if (!merged.deviceScreen) merged.deviceScreen = DEFAULTS.deviceScreen;
  if (!merged.buildStatus) merged.buildStatus = 'idle';
  if (!merged.deviceState) merged.deviceState = 'ready';
  if (!merged.projectName) merged.projectName = DEFAULT_PROJECT_NAME;
  if (!merged.goal) merged.goal = DEFAULT_GOAL;
  if (!merged.prompt) merged.prompt = DEFAULT_PROMPT;
  if (!merged.packageName) merged.packageName = 'com.example.browsernativeorchestrator';
  if (!merged.packageVersion) merged.packageVersion = '1.0.0';
  if (!merged.packageScreen) merged.packageScreen = 'Welcome to Browser Native Orchestrator';

  return merged;
}

function saveState() {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  } catch (error) {
    console.error(error);
  }
}

function loadState() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return;
    state = normalizeState(JSON.parse(raw));
  } catch (error) {
    console.error(error);
  }
}

function log(text) {
  state.logs = (state.logs || []).concat({
    id: Date.now(),
    text,
    time: nowTime(),
  }).slice(-80);
  saveState();
  render();
}

function setStatus(status, currentTask) {
  state.buildStatus = status;
  state.currentTask = currentTask || state.currentTask;
  saveState();
  render();
}

function getFile(path) {
  return state.files.find((file) => file.path === path);
}

function upsertFile(path, content, kind = 'code') {
  const existing = getFile(path);
  if (existing) {
    existing.content = content;
    existing.kind = kind || existing.kind;
    return existing;
  }
  const file = { path, content, kind };
  state.files.push(file);
  return file;
}

function ensureDefaultFiles() {
  const defaults = makeInitialFiles(state.projectName, state.goal, state.prompt);
  for (const file of defaults) {
    if (!getFile(file.path)) state.files.push(file);
  }
  state.files.sort((a, b) => a.path.localeCompare(b.path));
}

function selectedFileContent() {
  const file = getFile(state.selectedFile);
  return file ? file.content : '';
}

function extractTagText(source, tagName) {
  const pattern = new RegExp(`<${tagName}[^>]*>([\\s\\S]*?)<\\/${tagName}>`, 'i');
  const match = pattern.exec(source);
  if (!match) return '';
  return match[1]
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/\s+/g, ' ')
    .trim();
}

function deviceScreenFromSource(source) {
  const title = extractTagText(source, 'h1') || state.projectName;
  const subtitle = extractTagText(source, 'p') || state.goal;
  const promptText = extractTagText(source, 'pre') || state.prompt;
  return [
    title,
    '',
    subtitle,
    '',
    'Prompt:',
    promptText,
    '',
    'Stages:',
    state.tasks.map((task) => `${task.title} — ${task.status}`).join('\n'),
  ].join('\n');
}

function stageIndex(id) {
  return STAGES.findIndex((stage) => stage.id === id);
}

function updateTaskStatus(id, status, note) {
  const task = state.tasks.find((entry) => entry.id === id);
  if (!task) return;
  task.status = status;
  if (note) task.notes = (task.notes || []).concat(note);
}

function makeProjectReports() {
  const tasksJson = JSON.stringify(state.tasks, null, 2);
  const summary = [
    `# Project Summary`,
    '',
    `Name: ${state.projectName}`,
    `Goal: ${state.goal}`,
    `Prompt: ${state.prompt}`,
    `Package: ${state.packageName}`,
    `Version: ${state.packageVersion}`,
    `State: ${state.buildStatus}`,
    '',
    `Files: ${state.files.length}`,
    `Tasks: ${state.tasks.length}`,
  ].join('\n');

  return [
    { path: 'reports/state.json', kind: 'report', content: JSON.stringify(projectSnapshot(), null, 2) },
    { path: 'reports/tasks.json', kind: 'report', content: tasksJson },
    { path: 'reports/project-summary.md', kind: 'report', content: summary },
  ];
}

function projectSnapshot() {
  return {
    projectName: state.projectName,
    goal: state.goal,
    prompt: state.prompt,
    packageName: state.packageName,
    packageVersion: state.packageVersion,
    packageScreen: state.packageScreen,
    buildStatus: state.buildStatus,
    deviceState: state.deviceState,
    currentTask: state.currentTask,
    files: state.files,
    tasks: state.tasks,
    logs: state.logs,
    installedApps: state.installedApps,
    selectedFile: state.selectedFile,
    selectedWorker: state.selectedWorker,
    commandValue: state.commandValue,
    previewEnabled: state.previewEnabled,
    phoneMode: state.phoneMode,
    exportCount: state.exportCount,
    savedAt: state.savedAt,
    bundleName: state.bundleName,
  };
}

function generateBuilderArtifacts() {
  const appSource = generateAppSource(state.projectName, state.goal, state.prompt);
  const orchestratorSource = generateOrchestratorSource();
  const manifestJson = JSON.stringify({
    name: state.projectName,
    version: state.packageVersion,
    entry: 'src/App.tsx',
    packageName: state.packageName,
    goal: state.goal,
  }, null, 2);
  const bridgeJson = JSON.stringify({
    bridgeUrl: 'browser-native',
    installEndpoint: '/install',
    runEndpoint: '/run',
    bundleEndpoint: '/export',
  }, null, 2);
  const readme = [
    `# ${state.projectName}`,
    '',
    state.goal,
    '',
    '## Current build outputs',
    '- src/App.tsx',
    '- src/lib/orchestrator.ts',
    '- manifest.json',
    '- bridge/native-bridge-manifest.json',
  ].join('\n');

  return [
    { path: 'src/App.tsx', kind: 'code', content: appSource },
    { path: 'src/lib/orchestrator.ts', kind: 'code', content: orchestratorSource },
    { path: 'manifest.json', kind: 'config', content: manifestJson },
    { path: 'bridge/native-bridge-manifest.json', kind: 'config', content: bridgeJson },
    { path: 'README.md', kind: 'doc', content: readme },
  ];
}

function planStages() {
  return STAGES.map((stage, index) => makeStageTask(stage, index));
}

async function pause(ms = 100) {
  await new Promise((resolve) => setTimeout(resolve, ms));
}

function updateSelectedFileFromEditor(content) {
  state.files = state.files.map((file) => file.path === state.selectedFile ? { ...file, content } : file);
  if (state.selectedFile === 'src/App.tsx') {
    state.deviceScreen = deviceScreenFromSource(content);
  }
  saveState();
}

function setSelectedFile(path) {
  state.selectedFile = path;
  const file = getFile(path);
  if (file) {
    sourceDraft = file.content;
  }
  saveState();
  render();
}

function renderTaskList() {
  const target = qs('taskList');
  if (!target) return;
  target.innerHTML = state.tasks.map((task) => `
    <div class="item">
      <div>
        <div><strong>${escapeHtml(task.title)}</strong></div>
        <div class="muted">${escapeHtml(task.role)} • ${escapeHtml(task.notes?.[0] || 'Ready')}</div>
      </div>
      <div class="task-meta">
        <span class="pill pill-${task.status}">${escapeHtml(task.status)}</span>
        <button data-remove-task="${task.id}" class="mini">✕</button>
      </div>
    </div>
  `).join('');
}

function renderFileList() {
  const target = qs('fileList');
  if (!target) return;
  const filtered = state.files.filter((file) => file.path.toLowerCase().includes((state.searchText || '').toLowerCase()));
  target.innerHTML = filtered.map((file) => `
    <div class="item">
      <div>
        <div><strong>${escapeHtml(file.path)}</strong></div>
        <div class="muted">${escapeHtml(file.kind)}</div>
      </div>
      <button data-select-file="${escapeHtml(file.path)}" class="mini">›</button>
    </div>
  `).join('');
}

function renderLogs() {
  const target = qs('logs');
  if (!target) return;
  target.innerHTML = state.logs.map((logEntry) => `
    <div class="log">
      <span class="muted">${escapeHtml(logEntry.time)}</span>
      <span>${escapeHtml(logEntry.text)}</span>
    </div>
  `).join('');
}

function renderBuild() {
  const root = qs('content');
  root.innerHTML = document.getElementById('buildTemplate').innerHTML;

  qs('fileCount').textContent = String(state.files.length);
  qs('taskCount').textContent = String(state.tasks.length);
  qs('workerCount').textContent = String(state.workers.length);
  qs('selectedFileLabel').textContent = state.selectedFile;
  qs('statusLabel').textContent = `${state.buildStatus} • ${state.currentTask}`;
  qs('projectName').value = state.projectName;
  qs('goal').value = state.goal;
  qs('prompt').value = state.prompt;
  qs('editor').value = selectedFileContent() || sourceDraft || '';
  qs('taskInput').value = state.taskInput || '';
  qs('searchFiles').value = state.searchText || '';

  renderTaskList();
  renderFileList();
  renderLogs();

  qs('projectName').oninput = () => { state.projectName = qs('projectName').value; saveState(); };
  qs('goal').oninput = () => { state.goal = qs('goal').value; saveState(); };
  qs('prompt').oninput = () => { state.prompt = qs('prompt').value; saveState(); };
  qs('editor').oninput = () => {
    sourceDraft = qs('editor').value;
    updateSelectedFileFromEditor(sourceDraft);
    saveState();
  };
  qs('taskInput').oninput = () => { state.taskInput = qs('taskInput').value; saveState(); };
  qs('searchFiles').oninput = () => { state.searchText = qs('searchFiles').value; saveState(); renderBuild(); };
}

function renderDevice() {
  const root = qs('content');
  root.innerHTML = document.getElementById('deviceTemplate').innerHTML;

  qs('deviceStateLabel').textContent = state.deviceState;
  qs('installedCount').textContent = String(state.installedApps.length);
  qs('packageName').value = state.packageName;
  qs('packageVersion').value = state.packageVersion;
  qs('packageScreen').value = state.packageScreen;
  qs('packageDescription').value = state.goal;
  qs('commandOutput').textContent = state.commandOutput || 'Run a virtual command here.';
  qs('screen').textContent = state.deviceScreen;
  qs('installedList').innerHTML = state.installedApps.map((app) => `
    <div class="item">
      <div>
        <div><strong>${escapeHtml(app.name)}</strong></div>
        <div class="muted">${escapeHtml(app.packageName)}${app.running ? ' • running' : ''}</div>
      </div>
      <span class="pill pill-${app.running ? 'done' : 'queued'}">${app.running ? 'running' : 'installed'}</span>
    </div>
  `).join('');
  qs('deviceLogs').innerHTML = state.logs.map((logEntry) => `
    <div class="log">
      <span class="muted">${escapeHtml(logEntry.time)}</span>
      <span>${escapeHtml(logEntry.text)}</span>
    </div>
  `).join('');

  qs('command').value = state.commandValue || 'devices';
  qs('packageName').oninput = () => { state.packageName = qs('packageName').value; saveState(); };
  qs('packageVersion').oninput = () => { state.packageVersion = qs('packageVersion').value; saveState(); };
  qs('packageScreen').oninput = () => { state.packageScreen = qs('packageScreen').value; saveState(); };
  qs('packageDescription').oninput = () => { state.goal = qs('packageDescription').value; saveState(); };
  qs('command').oninput = () => { state.commandValue = qs('command').value; saveState(); };
}

function renderExport() {
  const root = qs('content');
  root.innerHTML = document.getElementById('exportTemplate').innerHTML;
  qs('exportCount').textContent = String(state.exportCount);
  qs('bundleLabel').textContent = state.bundleName || 'none';
  qs('savedLabel').textContent = state.savedAt ? 'yes' : 'no';
}

function renderSettings() {
  const root = qs('content');
  root.innerHTML = document.getElementById('settingsTemplate').innerHTML;
  qs('phoneMode').checked = Boolean(state.phoneMode);
  qs('previewMode').checked = Boolean(state.previewEnabled);
}

function renderHome() {
  const root = qs('content');
  root.innerHTML = `
    <section class="card stack">
      <div class="row">
        <div class="stat"><span>Project</span><strong>${escapeHtml(state.projectName)}</strong></div>
        <div class="stat"><span>Device</span><strong>${escapeHtml(state.deviceState)}</strong></div>
      </div>
      <div class="panel">
        <div class="panelHeader"><strong>Quick actions</strong></div>
        <div class="row">
          <button id="quickCompile" class="primary">Compile</button>
          <button id="quickInstall" class="secondary">Install</button>
          <button id="quickRun" class="secondary">Run</button>
          <button id="quickExport" class="secondary">Export</button>
        </div>
      </div>
      <div class="panel">
        <strong>What this mobile version does</strong>
        <div class="muted">Build projects, export bundles, and run them in the virtual device lab from Brave Mobile.</div>
      </div>
    </section>
  `;

  qs('quickCompile').onclick = compileProject;
  qs('quickInstall').onclick = installPackage;
  qs('quickRun').onclick = runApp;
  qs('quickExport').onclick = buildZip;
}

function renderTabs() {
  document.querySelectorAll('[data-tab]').forEach((button) => {
    button.classList.toggle('active', button.dataset.tab === activeTab);
    button.onclick = () => setTab(button.dataset.tab);
  });
}

function renderCommonBindings() {
  const installBtn = qs('installBtn');
  if (installBtn) {
    installBtn.hidden = false;
    installBtn.textContent = deferredPrompt ? 'Install app' : 'Install app';
    installBtn.onclick = async () => {
      if (deferredPrompt) {
        deferredPrompt.prompt();
        try {
          await deferredPrompt.userChoice;
        } catch (error) {
          console.warn(error);
        }
        deferredPrompt = null;
        installBtn.hidden = true;
        log('Install prompt completed.');
      } else {
        state.commandOutput = 'Open Brave menu → Add to Home Screen.';
        log('Install prompt not available yet. Use the browser menu to add the app to your home screen.');
        render();
      }
    };
  }

  qs('saveBtn').onclick = () => {
    state.savedAt = new Date().toISOString();
    log('Project saved locally.');
    render();
  };

  qs('exportBtn').onclick = buildZip;

  document.querySelectorAll('[data-select-file]').forEach((button) => {
    button.onclick = () => setSelectedFile(button.dataset.selectFile);
  });

  document.querySelectorAll('[data-remove-task]').forEach((button) => {
    button.onclick = () => {
      state.tasks = state.tasks.filter((task) => task.id !== button.dataset.removeTask);
      log('Task removed.');
      render();
    };
  });

  const addTaskBtn = qs('addTaskBtn');
  if (addTaskBtn) addTaskBtn.onclick = addTask;

  const addFileBtn = qs('addFileBtn');
  if (addFileBtn) addFileBtn.onclick = addFile;

  const draftBtn = qs('draftBtn');
  if (draftBtn) draftBtn.onclick = generateDraft;

  const compileBtn = qs('compileBtn');
  if (compileBtn) compileBtn.onclick = compileProject;

  const installDeviceBtn = qs('installDeviceBtn');
  if (installDeviceBtn) installDeviceBtn.onclick = installPackage;

  const runDeviceBtn = qs('runDeviceBtn');
  if (runDeviceBtn) runDeviceBtn.onclick = runApp;

  const resetDeviceBtn = qs('resetDeviceBtn');
  if (resetDeviceBtn) resetDeviceBtn.onclick = resetDevice;

  const runCmdBtn = qs('runCmdBtn');
  if (runCmdBtn) runCmdBtn.onclick = runCommand;

  const buildZipBtn = qs('buildZipBtn');
  if (buildZipBtn) buildZipBtn.onclick = buildZip;

  const snapshotBtn = qs('snapshotBtn');
  if (snapshotBtn) snapshotBtn.onclick = snapshotProject;

  const importBtn = qs('importBtn');
  if (importBtn) importBtn.onclick = () => qs('importFile').click();

  const importFile = qs('importFile');
  if (importFile) importFile.onchange = async (event) => {
    const file = event.target.files[0];
    if (file) await importState(file);
    event.target.value = '';
  };

  const resetAllBtn = qs('resetAllBtn');
  if (resetAllBtn) resetAllBtn.onclick = resetAll;

  const phoneModeEl = qs('phoneMode');
  if (phoneModeEl) phoneModeEl.onchange = () => { state.phoneMode = phoneModeEl.checked; saveState(); };
  const previewModeEl = qs('previewMode');
  if (previewModeEl) previewModeEl.onchange = () => { state.previewEnabled = previewModeEl.checked; saveState(); };

  ['projectName', 'goal', 'prompt', 'packageName', 'packageVersion', 'packageScreen', 'packageDescription', 'editor', 'taskInput', 'searchFiles', 'command'].forEach((id) => {
    const el = qs(id);
    if (!el) return;
    el.addEventListener('input', () => {
      if (id === 'command') return;
      if (id === 'editor') return;
      saveState();
    });
  });
}

function render() {
  if (activeTab === 'build') renderBuild();
  else if (activeTab === 'device') renderDevice();
  else if (activeTab === 'export') renderExport();
  else if (activeTab === 'settings') renderSettings();
  else renderHome();

  renderTabs();
  renderCommonBindings();
  saveState();
}

function setTab(tab) {
  activeTab = tab;
  render();
}

function addTask() {
  const title = (state.taskInput || '').trim();
  if (!title) {
    state.commandOutput = 'Type a task title first.';
    render();
    return;
  }
  const id = `custom-${Date.now()}`;
  state.tasks.push({ id, title, role: 'builder', status: 'queued', notes: [] });
  state.taskInput = '';
  state.commandOutput = `Task added: ${title}`;
  log(`Task added: ${title}`);
  render();
}

function addFile() {
  const number = state.files.filter((file) => file.path.startsWith('src/generated/file-')).length + 1;
  const path = `src/generated/file-${number}.ts`;
  const content = `export const value${number} = ${number};`;
  state.files.push({ path, kind: 'code', content });
  state.selectedFile = path;
  sourceDraft = content;
  state.deviceScreen = deviceScreenFromSource(content);
  log(`Created ${path}.`);
  render();
}

function generateDraft() {
  const draft = generateAppSource(state.projectName, state.goal, state.prompt);
  state.selectedFile = 'src/App.tsx';
  sourceDraft = draft;
  upsertFile('src/App.tsx', draft, 'code');
  state.commandOutput = 'Draft generated from the current prompt.';
  log('Prompt converted into source draft.');
  render();
}

async function compileProject() {
  if (state.buildStatus === 'building') return;

  ensureDefaultFiles();
  state.buildStatus = 'building';
  state.currentTask = 'Initializing compiler pipeline';
  state.commandOutput = 'Compiler started.';
  const customTasks = state.tasks.filter((task) => !STAGES.some((stage) => stage.id === task.id));
  state.tasks = [...planStages(), ...customTasks];
  log('Planner created the task flow.');
  render();
  await pause(120);

  const stages = [
    {
      id: 'planner',
      run: () => {
        const report = [
          '# Plan',
          '',
          `Project: ${state.projectName}`,
          `Goal: ${state.goal}`,
          `Prompt: ${state.prompt}`,
        ].join('\n');
        upsertFile('reports/plan.md', report, 'report');
        upsertFile('reports/tasks.json', JSON.stringify(state.tasks, null, 2), 'report');
        state.workers = state.workers.map((worker) => worker.id === 'planner' ? { ...worker, status: 'Complete' } : worker);
      },
    },
    {
      id: 'architect',
      run: () => {
        const report = [
          '# Architecture',
          '',
          '- Browser-first PWA shell',
          '- Mobile-friendly device simulator',
          '- Project files + exported bundles',
          '- Multi-stage compiler pipeline',
        ].join('\n');
        upsertFile('reports/architecture.md', report, 'report');
        state.workers = state.workers.map((worker) => worker.id === 'architect' ? { ...worker, status: 'Complete' } : worker);
      },
    },
    {
      id: 'builder',
      run: () => {
        const generated = generateBuilderArtifacts();
        generated.forEach((file) => upsertFile(file.path, file.content, file.kind));
        state.selectedFile = 'src/App.tsx';
        sourceDraft = getFile('src/App.tsx').content;
        state.workers = state.workers.map((worker) => worker.id === 'builder' ? { ...worker, status: 'Complete' } : worker);
      },
    },
    {
      id: 'critic',
      run: () => {
        const missing = ['src/App.tsx', 'src/lib/orchestrator.ts', 'manifest.json', 'bridge/native-bridge-manifest.json']
          .filter((path) => !getFile(path));
        const report = [
          '# Review',
          '',
          missing.length ? `Missing: ${missing.join(', ')}` : 'Review passed: all required artifacts present.',
        ].join('\n');
        upsertFile('reports/review.md', report, 'report');
        state.workers = state.workers.map((worker) => worker.id === 'critic' ? { ...worker, status: missing.length ? 'Needs work' : 'Complete' } : worker);
      },
    },
    {
      id: 'tester',
      run: () => {
        const source = getFile('src/App.tsx')?.content || '';
        const passed = /export default function App/.test(source) && /<h1>/.test(source);
        const report = [
          '# Validation',
          '',
          passed ? 'Validation passed.' : 'Validation failed: App shell missing.',
        ].join('\n');
        upsertFile('reports/tests.md', report, 'report');
        state.workers = state.workers.map((worker) => worker.id === 'tester' ? { ...worker, status: passed ? 'Complete' : 'Needs work' } : worker);
      },
    },
    {
      id: 'packager',
      run: () => {
        upsertFile('bridge/native-bridge-manifest.json', JSON.stringify({
          bridgeUrl: 'browser-native',
          installEndpoint: '/install',
          runEndpoint: '/run',
          bundleEndpoint: '/export',
          buildStatus: state.buildStatus,
        }, null, 2), 'config');
        upsertFile('reports/handoff.md', [
          '# Handoff',
          '',
          `Project: ${state.projectName}`,
          `Goal: ${state.goal}`,
          `Package: ${state.packageName}`,
          `Version: ${state.packageVersion}`,
        ].join('\n'), 'report');
        state.workers = state.workers.map((worker) => worker.id === 'packager' ? { ...worker, status: 'Complete' } : worker);
      },
    },
    {
      id: 'runner',
      run: () => {
        state.deviceState = 'running';
        state.installedApps = [{
          name: state.projectName,
          packageName: state.packageName,
          version: state.packageVersion,
          running: true,
          lastLaunched: new Date().toISOString(),
        }];
        state.deviceScreen = deviceScreenFromSource(getFile('src/App.tsx')?.content || sourceDraft || '');
        upsertFile('reports/device-log.txt', `Launched ${state.projectName} in browser-native device lab at ${new Date().toISOString()}.`, 'report');
        state.workers = state.workers.map((worker) => worker.id === 'runner' ? { ...worker, status: 'Complete' } : worker);
      },
    },
  ];

  for (const stage of stages) {
    state.currentTask = stage.title;
    updateTaskStatus(stage.id, 'running', 'Running');
    log(`${stage.title} started.`);
    render();
    await pause(140);
    stage.run();
    updateTaskStatus(stage.id, 'done', 'Complete');
    log(`${stage.title} complete.`);
    render();
    await pause(100);
  }

  state.buildStatus = 'ready';
  state.currentTask = 'Compiler ready';
  state.commandOutput = 'Compiler run completed successfully.';
  state.deviceScreen = deviceScreenFromSource(getFile('src/App.tsx')?.content || sourceDraft || '');
  ensureDefaultFiles();
  saveState();
  log('Compiler run completed.');
  render();
}

function installPackage() {
  if (!getFile('src/App.tsx')) {
    state.commandOutput = 'Nothing to install yet. Run the compiler first.';
    log('Install attempted before compile.');
    render();
    return;
  }
  state.deviceState = 'installed';
  state.installedApps = [{
    name: state.projectName,
    packageName: state.packageName,
    version: state.packageVersion,
    running: false,
    lastLaunched: null,
  }];
  state.deviceScreen = deviceScreenFromSource(getFile('src/App.tsx').content);
  state.commandOutput = `Installed ${state.packageName} into the virtual device.`;
  log(`Installed ${state.projectName}.`);
  render();
}

function runApp() {
  if (!state.installedApps.length) {
    installPackage();
  }
  state.deviceState = 'running';
  state.installedApps = state.installedApps.map((app) => ({ ...app, running: true, lastLaunched: new Date().toISOString() }));
  state.deviceScreen = deviceScreenFromSource(getFile('src/App.tsx')?.content || sourceDraft || '');
  state.commandOutput = `Launching ${state.packageName}...`;
  log(`Running ${state.projectName} on the mobile emulator.`);
  render();
}

function resetDevice() {
  state.deviceState = 'ready';
  state.installedApps = [];
  state.deviceScreen = DEFAULTS.deviceScreen;
  state.commandOutput = 'Device reset to ready state.';
  log('Virtual device reset.');
  render();
}

function runCommand() {
  const c = String(state.commandValue || '').trim().toLowerCase();
  if (!c) return;
  if (c === 'help') {
    state.commandOutput = [
      'devices',
      'install',
      'shell am start',
      'logcat',
      'reboot',
    ].join('\n');
    log('Help command shown.');
  } else if (c.includes('devices')) {
    state.commandOutput = state.installedApps.length
      ? `List of devices attached\nmobile-lab-001\tdevice\n${state.packageName}\t${state.deviceState}`
      : 'List of devices attached\nmobile-lab-001\tdevice';
    log('devices command handled.');
  } else if (c.includes('install')) {
    installPackage();
    return;
  } else if (c.includes('shell am start')) {
    runApp();
    return;
  } else if (c.includes('logcat')) {
    state.commandOutput = state.logs.slice(-10).map((entry) => `[${entry.time}] ${entry.text}`).join('\n');
    log('logcat captured.');
  } else if (c.includes('reboot')) {
    resetDevice();
    state.commandOutput = 'Rebooting virtual device...';
  } else {
    state.commandOutput = `Command accepted: ${state.commandValue}`;
    log(`Command handled: ${state.commandValue}`);
  }
  render();
}

function snapshotProject() {
  state.savedAt = new Date().toISOString();
  state.exportCount += 1;
  state.bundleName = `${slugify(state.projectName)}-snapshot-${state.exportCount}.json`;
  log('Snapshot captured.');
  render();
}

function resetAll() {
  state = clone(DEFAULTS);
  activeTab = 'home';
  deferredPrompt = null;
  sourceDraft = getFile('src/App.tsx')?.content || DEFAULTS.files[0].content;
  log('Project reset to defaults.');
  render();
}

function slugify(text) {
  return String(text)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    || 'browser-native-orchestrator';
}

function toUint8Array(value) {
  if (value instanceof Uint8Array) return value;
  if (typeof value === 'string') return new TextEncoder().encode(value);
  if (value instanceof ArrayBuffer) return new Uint8Array(value);
  throw new TypeError('Unsupported data type');
}

function makeCrc32Table() {
  const table = new Uint32Array(256);
  for (let n = 0; n < 256; n += 1) {
    let c = n;
    for (let k = 0; k < 8; k += 1) {
      c = ((c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1)) >>> 0;
    }
    table[n] = c >>> 0;
  }
  return table;
}

const CRC32_TABLE = makeCrc32Table();

function crc32(data) {
  const bytes = toUint8Array(data);
  let c = 0xFFFFFFFF;
  for (let i = 0; i < bytes.length; i += 1) {
    c = CRC32_TABLE[(c ^ bytes[i]) & 0xFF] ^ (c >>> 8);
  }
  return (c ^ 0xFFFFFFFF) >>> 0;
}

function makeDosDateTime(date = new Date()) {
  const year = Math.max(1980, date.getFullYear()) - 1980;
  const month = date.getMonth() + 1;
  const day = date.getDate();
  const hours = date.getHours();
  const minutes = date.getMinutes();
  const seconds = Math.floor(date.getSeconds() / 2);
  const dosDate = (year << 9) | (month << 5) | day;
  const dosTime = (hours << 11) | (minutes << 5) | seconds;
  return { dosDate, dosTime };
}

function writeUint16LE(view, offset, value) {
  view.setUint16(offset, value & 0xFFFF, true);
}

function writeUint32LE(view, offset, value) {
  view.setUint32(offset, value >>> 0, true);
}

function concatChunks(chunks) {
  const total = chunks.reduce((sum, chunk) => sum + chunk.length, 0);
  const out = new Uint8Array(total);
  let offset = 0;
  for (const chunk of chunks) {
    out.set(chunk, offset);
    offset += chunk.length;
  }
  return out;
}

function createZipBlob(entries) {
  const fileEntries = entries.map((entry) => ({
    name: entry.name.replace(/\\/g, '/'),
    data: toUint8Array(entry.data),
  }));

  const localChunks = [];
  const centralChunks = [];
  const offsets = [];
  let cursor = 0;
  const { dosDate, dosTime } = makeDosDateTime();

  for (const entry of fileEntries) {
    const nameBytes = toUint8Array(entry.name);
    const dataBytes = entry.data;
    const crc = crc32(dataBytes);

    const localHeader = new Uint8Array(30 + nameBytes.length);
    const localView = new DataView(localHeader.buffer);
    writeUint32LE(localView, 0, 0x04034b50);
    writeUint16LE(localView, 4, 20);
    writeUint16LE(localView, 6, 0);
    writeUint16LE(localView, 8, 0);
    writeUint16LE(localView, 10, dosTime);
    writeUint16LE(localView, 12, dosDate);
    writeUint32LE(localView, 14, crc);
    writeUint32LE(localView, 18, dataBytes.length);
    writeUint32LE(localView, 22, dataBytes.length);
    writeUint16LE(localView, 26, nameBytes.length);
    writeUint16LE(localView, 28, 0);
    localHeader.set(nameBytes, 30);

    offsets.push(cursor);
    localChunks.push(localHeader, dataBytes);
    cursor += localHeader.length + dataBytes.length;
  }

  let centralSize = 0;
  for (let i = 0; i < fileEntries.length; i += 1) {
    const entry = fileEntries[i];
    const nameBytes = toUint8Array(entry.name);
    const dataBytes = entry.data;
    const crc = crc32(dataBytes);
    const localOffset = offsets[i];

    const centralHeader = new Uint8Array(46 + nameBytes.length);
    const centralView = new DataView(centralHeader.buffer);
    writeUint32LE(centralView, 0, 0x02014b50);
    writeUint16LE(centralView, 4, 20);
    writeUint16LE(centralView, 6, 20);
    writeUint16LE(centralView, 8, 0);
    writeUint16LE(centralView, 10, 0);
    writeUint16LE(centralView, 12, dosTime);
    writeUint16LE(centralView, 14, dosDate);
    writeUint32LE(centralView, 16, crc);
    writeUint32LE(centralView, 20, dataBytes.length);
    writeUint32LE(centralView, 24, dataBytes.length);
    writeUint16LE(centralView, 28, nameBytes.length);
    writeUint16LE(centralView, 30, 0);
    writeUint16LE(centralView, 32, 0);
    writeUint16LE(centralView, 34, 0);
    writeUint16LE(centralView, 36, 0);
    writeUint32LE(centralView, 38, 0);
    writeUint32LE(centralView, 42, localOffset);
    centralHeader.set(nameBytes, 46);

    centralChunks.push(centralHeader);
    centralSize += centralHeader.length;
  }

  const localData = concatChunks(localChunks);
  const centralData = concatChunks(centralChunks);
  const endRecord = new Uint8Array(22);
  const endView = new DataView(endRecord.buffer);
  writeUint32LE(endView, 0, 0x06054b50);
  writeUint16LE(endView, 4, 0);
  writeUint16LE(endView, 6, 0);
  writeUint16LE(endView, 8, fileEntries.length);
  writeUint16LE(endView, 10, fileEntries.length);
  writeUint32LE(endView, 12, centralData.length);
  writeUint32LE(endView, 16, localData.length);
  writeUint16LE(endView, 20, 0);

  return new Blob([localData, centralData, endRecord], { type: 'application/zip' });
}

async function fetchText(path) {
  const response = await fetch(path, { cache: 'no-store' });
  if (!response.ok) throw new Error(`Failed to fetch ${path}`);
  return await response.text();
}

async function fetchBinary(path) {
  const response = await fetch(path, { cache: 'no-store' });
  if (!response.ok) throw new Error(`Failed to fetch ${path}`);
  return await response.arrayBuffer();
}

async function collectShellFiles() {
  const files = [];
  const textPaths = ['index.html', 'app.js', 'styles.css', 'manifest.webmanifest', 'sw.js', 'README.md'];
  for (const path of textPaths) {
    try {
      files.push({ name: `workspace/${path}`, data: await fetchText(`./${path}`) });
    } catch (error) {
      console.warn(error);
    }
  }

  const binaryPaths = ['assets/icon-192.png', 'assets/icon-512.png'];
  for (const path of binaryPaths) {
    try {
      files.push({ name: `workspace/${path}`, data: await fetchBinary(`./${path}`) });
    } catch (error) {
      console.warn(error);
    }
  }

  return files;
}

async function buildZip() {
  try {
    const projectFiles = state.files.map((file) => ({ name: `project/${file.path}`, data: file.content }));
    const reportFiles = makeProjectReports().map((file) => ({ name: `reports/${file.path.replace(/^reports\//, '')}`, data: file.content }));
    const shellFiles = await collectShellFiles();
    const bundle = {
      generatedAt: new Date().toISOString(),
      project: projectSnapshot(),
    };

    const zip = buildZipFromEntries([
      ...shellFiles,
      ...projectFiles,
      ...reportFiles,
      { name: 'bundle.json', data: JSON.stringify(bundle, null, 2) },
    ]);

    const filename = `${slugify(state.projectName)}-bundle.zip`;
    downloadBlob(zip, filename);
    state.bundleName = filename;
    state.exportCount += 1;
    state.savedAt = new Date().toISOString();
    log(`Exported bundle: ${filename}`);
  } catch (error) {
    state.commandOutput = `Export failed: ${error.message}`;
    log(`Export failed: ${error.message}`);
  }
}

function buildZipFromEntries(entries) {
  return createZipBlob(entries);
}

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}

async function importState(file) {
  try {
    const text = await file.text();
    const parsed = JSON.parse(text);
    state = normalizeState(parsed.project || parsed);
    state.savedAt = new Date().toISOString();
    state.bundleName = file.name;
    if (parsed.project && Array.isArray(parsed.project.files)) {
      state.files = parsed.project.files.map(normalizeFile).filter(Boolean);
    }
    log('State imported from JSON.');
  } catch (error) {
    state.commandOutput = 'Import failed: please choose a JSON state file.';
    log(`Import failed: ${error.message}`);
  }
  render();
}

function onGlobalError(message) {
  state.commandOutput = message;
  log(message);
}

window.addEventListener('error', (event) => {
  onGlobalError(`Error: ${event.message}`);
});

window.addEventListener('unhandledrejection', (event) => {
  const reason = event.reason && event.reason.message ? event.reason.message : String(event.reason);
  onGlobalError(`Promise rejection: ${reason}`);
});

window.addEventListener('beforeinstallprompt', (event) => {
  event.preventDefault();
  deferredPrompt = event;
  const installBtn = qs('installBtn');
  if (installBtn) installBtn.hidden = false;
  log('Install prompt is available.');
});

window.addEventListener('appinstalled', () => {
  log('App installed.');
});

async function registerServiceWorker() {
  if (!('serviceWorker' in navigator)) return;
  try {
    await navigator.serviceWorker.register('./sw.js', { scope: './' });
    log('Offline cache ready.');
  } catch (error) {
    console.warn(error);
  }
}

function handleMenuButtons() {
  const menuButtons = document.querySelectorAll('[data-tab]');
  menuButtons.forEach((button) => {
    button.onclick = () => setTab(button.dataset.tab);
  });
}

function initFileSelectorListeners() {
  document.querySelectorAll('[data-select-file]').forEach((button) => {
    button.onclick = () => setSelectedFile(button.dataset.selectFile);
  });
  document.querySelectorAll('[data-remove-task]').forEach((button) => {
    button.onclick = () => {
      state.tasks = state.tasks.filter((task) => task.id !== button.dataset.removeTask);
      log('Task removed.');
      render();
    };
  });
}

function wirePersistentControls() {
  // Field bindings are assigned within each tab render.
}

function render() {
  if (activeTab === 'build') renderBuild();
  else if (activeTab === 'device') renderDevice();
  else if (activeTab === 'export') renderExport();
  else if (activeTab === 'settings') renderSettings();
  else renderHome();

  renderTabs();
  renderCommonBindings();
  initFileSelectorListeners();
  wirePersistentControls();
  saveState();
}

function initializeDefaults() {
  if (!state.files || !state.files.length) {
    state.files = makeInitialFiles(state.projectName, state.goal, state.prompt);
  }
  if (!state.tasks || !state.tasks.length) {
    state.tasks = planStages();
  }
  if (!state.workers || !state.workers.length) {
    state.workers = STAGES.map(makeWorker);
  }
  if (!state.logs) state.logs = [];
  if (!state.installedApps) state.installedApps = [];
  if (!state.selectedFile) state.selectedFile = 'src/App.tsx';
  if (!getFile(state.selectedFile)) {
    state.selectedFile = state.files[0]?.path || 'src/App.tsx';
  }
  if (!state.deviceScreen) state.deviceScreen = DEFAULTS.deviceScreen;
}

async function start() {
  loadState();
  state = normalizeState(state);
  initializeDefaults();
  sourceDraft = selectedFileContent();
  if (state.selectedFile === 'src/App.tsx' && sourceDraft) {
    state.deviceScreen = deviceScreenFromSource(sourceDraft);
  }
  render();
  await registerServiceWorker();
  log('Workspace ready.');
}

let sourceDraft = '';
start();
